# Change the values of <token>, <id>, <title> and <content> to the desired ones.
# To obtain the token, log in to the application and copy the authorization header token.
# The token is valid for 1 hour.

### Login - generate token
POST http://localhost:1084/auth/login
Content-Type: application/json

{
    "username": "<name>",
    "password": "<password>"
}

### Register - create new user
POST http://localhost:1084/auth/register
Content-Type: application/json

{
    "username": "<name>",
    "password": "<password>"
}

### Get all users
GET http://localhost:1084/auth/users
Authorization: Bearer <token>

### PATH - change user's role
PATCH http://localhost:1084/auth/update/<id>/role
Authorization: Bearer <token>
Content-Type: application/json

{
    "role": "<role>"
}
