### GET
GET http://localhost:1084/submission

### GET BY ID - change id for tests
GET http://localhost:1084/submission/filter?id=c6be3e79-1c57-4f33-8fc8-dec25f61f738
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzY0MTcxLCJleHAiOjE3NDUzNjc3NzF9.9cxPCyzRV5PI6v1QZzfFkABda2xzgvgdWP_HvM0AXiI

### GET BY TITLE
GET http://localhost:1084/submission/filter?title=maior

### REGISTER NEW SUBMISSIONS
POST http://localhost:1084/submission/register
Content-Type: application/json

{
    "title": "Maior",
    "content": "loren ipsun"
}


### DELETE A SUBMISSION BY ID - change id for tests
DELETE http://localhost:1084/submission/delete/21d3179d-dcf3-48be-b30f-f46564bfe45e

### UPDATE A SUBMISSION - change id for tests
PATCH  http://localhost:1084/submission/update/21d3179d-dcf3-48be-b30f-f46564bfe45e
Content-Type: application/json

{
    "title": "novo novo title",
    "content": "content novo"
}